### ISSUE TITLE
[1-1-1 ]The database is integrated, the content is queried from it

### ISSUE THREAD

**Issue by KamilKrauze** [KamilKrauze/agile_project#40]
## Acceptance Criteria
- A PHP database linking file for the webpages to access the MySQL DB's information.

**Comment by last-genius** [comment]
Delete this branch entirely, with all of its contents (see something like [this](https://dev.to/morinoko/useful-git-commands-for-removing-accidentally-pushed-or-committed-files-2ld)) because it is extremely insecure to upload private things like this into a repository (whether it's public or not). Our database is sort of protected because we have to add IPs into Azure but this is not enough, since posting its address, password and the SSL certificate publicly compromises the entire thing. 

We can use something like [encrypted secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets) to fix this.
